version: '2'
services:
  pokemon_db:
    image: postgres
    container_name: pokemon_db
    volumes:
      - "pokemon_data:/var/lib/postgres/data"
  web:
    build:
      context: ./web
      args:
        env: dev
    command: sh -c "python manage.py collectstatic --noinput; python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    volumes: 
      - ./web:/app
      - ./static:/static
      - ./media:/media
    depends_on:
      - pokemon_db
    ports:
      - "8000:8000"

volumes:
  pokemon_data:
