# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('can_breed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EggMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LevelUpMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('move_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PokeEggGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_egg_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Moves')),
                ('name', models.ManyToManyField(to='pokemon_app.EggGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PokeGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Genderless')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('is_evolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PokeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_number', models.ManyToManyField(to='pokemon_app.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='poketype',
            name='type_num',
            field=models.ManyToManyField(to='pokemon_app.Type'),
        ),
        migrations.AddField(
            model_name='pokegender',
            name='poke_number',
            field=models.ManyToManyField(to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokeegggroup',
            name='poke_number',
            field=models.ManyToManyField(to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='levelupmoves',
            name='move_num',
            field=models.ManyToManyField(to='pokemon_app.Moves'),
        ),
        migrations.AddField(
            model_name='levelupmoves',
            name='poke_number',
            field=models.ManyToManyField(to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='eggmoves',
            name='move_num',
            field=models.ManyToManyField(to='pokemon_app.Moves'),
        ),
        migrations.AddField(
            model_name='eggmoves',
            name='poke_number',
            field=models.ManyToManyField(to='pokemon_app.Pokemon'),
        ),
    ]
