# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('can_breed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTrios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LevelUpMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('move_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('is_evolved', models.BooleanField(default=False)),
                ('female_ratio', models.FloatField(default=0)),
                ('male_ratio', models.FloatField(default=0)),
                ('picture', models.CharField(default='picture', max_length=100)),
                ('egg_groups', models.ManyToManyField(to='pokemon_app.EggGroup')),
                ('egg_moves', models.ManyToManyField(related_name='pokemon_egg_move', to='pokemon_app.Moves')),
                ('level_up_moves', models.ManyToManyField(through='pokemon_app.LevelUpMove', to='pokemon_app.Moves')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='type_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(to='pokemon_app.Type'),
        ),
        migrations.AddField(
            model_name='levelupmove',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Moves'),
        ),
        migrations.AddField(
            model_name='levelupmove',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='historytrios',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytrios_child', to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='historytrios',
            name='child_egg_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytrios_child_egg_move', to='pokemon_app.Moves'),
        ),
        migrations.AddField(
            model_name='historytrios',
            name='parent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytrios_parent_1', to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='historytrios',
            name='parent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytrios_parent_2', to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='historytrios',
            name='parent_level_up_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytrios_parent_level_up_move', to='pokemon_app.Moves'),
        ),
        migrations.AddField(
            model_name='historytrios',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
