# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_auto_20171122_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Genderless')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LevelUpMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('move_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Moves')),
            ],
        ),
        migrations.RemoveField(
            model_name='eggmoves',
            name='move_num',
        ),
        migrations.RemoveField(
            model_name='eggmoves',
            name='poke_number',
        ),
        migrations.RemoveField(
            model_name='levelupmoves',
            name='move_num',
        ),
        migrations.RemoveField(
            model_name='levelupmoves',
            name='poke_number',
        ),
        migrations.RemoveField(
            model_name='pokeegggroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pokeegggroup',
            name='poke_number',
        ),
        migrations.RemoveField(
            model_name='pokegender',
            name='poke_number',
        ),
        migrations.RemoveField(
            model_name='poketype',
            name='poke_number',
        ),
        migrations.RemoveField(
            model_name='poketype',
            name='type_num',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_groups',
            field=models.ManyToManyField(to='pokemon_app.EggGroup'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_moves',
            field=models.ManyToManyField(related_name='pokemon_egg_move', to='pokemon_app.Moves'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(to='pokemon_app.Type'),
        ),
        migrations.DeleteModel(
            name='EggMoves',
        ),
        migrations.DeleteModel(
            name='LevelUpMoves',
        ),
        migrations.DeleteModel(
            name='PokeEggGroup',
        ),
        migrations.DeleteModel(
            name='PokeGender',
        ),
        migrations.DeleteModel(
            name='PokeType',
        ),
        migrations.AddField(
            model_name='levelupmove',
            name='poke_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='genders',
            field=models.ManyToManyField(to='pokemon_app.Gender'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='level_up_moves',
            field=models.ManyToManyField(through='pokemon_app.LevelUpMove', to='pokemon_app.Moves'),
        ),
    ]
