# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_auto_20171122_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytrios',
            name='child',
        ),
        migrations.RemoveField(
            model_name='historytrios',
            name='child_egg_move',
        ),
        migrations.RemoveField(
            model_name='historytrios',
            name='parent1',
        ),
        migrations.RemoveField(
            model_name='historytrios',
            name='parent2',
        ),
        migrations.RemoveField(
            model_name='historytrios',
            name='parent_level_up_move',
        ),
        migrations.RemoveField(
            model_name='historytrios',
            name='username',
        ),
        migrations.DeleteModel(
            name='HistoryTrios',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
