# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0007_historytrios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Pokemon')),
                ('type_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Type')),
            ],
        ),
    ]
