# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0008_pokemontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemontype',
            old_name='poke_number',
            new_name='poke_num',
        ),
    ]
