# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0009_auto_20171201_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelupmove',
            old_name='move_num',
            new_name='move',
        ),
        migrations.RenameField(
            model_name='levelupmove',
            old_name='poke_number',
            new_name='pokemon',
        ),
    ]
