# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0010_auto_20171202_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='genders',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='female_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='male_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='picture_path',
            field=models.CharField(default='picture', max_length=100),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
