# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0011_auto_20171202_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='picture_path',
            new_name='picture',
        ),
    ]
